### ISSUE TITLE
С переходом на новую форму авторизации...

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#125]
У нас нигде в приложении нет ссылки "забыли пароль?" может можно её в форме разместить (маленькую)? Пускай она выбрасывает на сайт в браузер (не веб-вью), но таки будет, ибо тут недавно сильно это помешало и мне отписались о том что у нас там ссылка отсутствует!

**Comment by fokin33** [comment]
Конечно можно, нужен только адрес ссылки собственно

25 апреля 2017 г., 19:50 пользователь Moshkov Konstantin <
notifications@github.com> написал:

**Comment by GaMsh** [comment]
https://osmo.mobi/forgot
