### ISSUE TITLE
Css problem make html tracking impossible 

### ISSUE THREAD

**Issue by brunetton** [OpenStreetMap-Monitoring/OsMoDroid#132]
Hi, I often use OsMoDroid with friends and we love it. Today I wanted to use it with my mother who hadn't installed the app. But unfortunately she wasn't able to see the osm tiles because the default map is set to humanitarian map (that's inexistant in France, where I live) and due to a css problem, she wasn't able to change the background map (see screenshot). 
On this screenshot I managed to change the background to set it to standard osm, but the css problem is still visible. 
This device's screen is 540x960.

Thanks ! 
![screenshot_2017-12-28-22-13-37](https://user-images.githubusercontent.com/86322/34423773-a88ee652-ec1e-11e7-94de-b84040f3fd2a.png)

**Comment by brunetton** [comment]
Can you please just explain why did you closed this ticket, without any explanation? Thanks

**Comment by GaMsh** [comment]
This ticket not about OsMoDroid apps.

**Comment by brunetton** [comment]
Indeed, but closely linked.
I don't see any git repo for the website :
- OsMoWP
- iOsMo
- OsMo.mobi-texts

These repos doesn't seem to be the good projet for reporting website issues. So, where is the correct place to report that ? 
By the way, I could probably easily fix the problem and make a pull request. 
Thanks !

**Comment by GaMsh** [comment]
You can write to support: osmo.mobi@gmail.com

**Comment by brunetton** [comment]
Thanks!

Le 3 janv. 2018 14:42, "Moshkov Konstantin" <notifications@github.com> a
écrit :
