### ISSUE TITLE
не пишет трек в режиме самолёта

### ISSUE THREAD

**Issue by progserega** [OpenStreetMap-Monitoring/OsMoDroid#134]
Координаты есть, место на диске есть, но в статитсике пусто (зато в буфере есть точки), а в треке - лишь пара точек, хотя запись шла пару часов.
В настройках стоит запись трека с периодом 1000 мс. Все остальные параметры записи - нули.

Логи и скриншоты - во вложении.
[debug-07-07-18.txt](https://github.com/OsMo-lab/OsMoDroid/files/2176273/debug-07-07-18.txt)
![screenshot_20180707-170208](https://user-images.githubusercontent.com/1297163/42452768-6075ea44-83ce-11e8-9647-462a6cab03ae.png)
![screenshot_20180707-170220](https://user-images.githubusercontent.com/1297163/42452769-60aa5608-83ce-11e8-8684-0007acfbb8f8.png)
![screenshot_20180707-174051](https://user-images.githubusercontent.com/1297163/42452770-60e3b8b2-83ce-11e8-8175-d37b79715cf6.png)
![screenshot_20180707-182241](https://user-images.githubusercontent.com/1297163/42452772-614dea34-83ce-11e8-9e7b-ec0e8e3e1558.png)
![screenshot_20180707-182249](https://user-images.githubusercontent.com/1297163/42452773-61824ef0-83ce-11e8-9c28-0fcb8328b89c.png)
[20180707143255.gpx.gz](https://github.com/OsMo-lab/OsMoDroid/files/2176276/20180707143255.gpx.gz)

**Comment by fokin33** [comment]
Все настройки в параметрах записи посмотреть бы ?

**Comment by GaMsh** [comment]
Здравствуйте!

Необходим пример трека записываемого паралельно иным приложением или скринкаст главного экрана приложения во время записи. 

Мы не смогли повторить такую же ситуацию, проблем записью нет, не зависимо от наличия сети.

**Comment by progserega** [comment]
Настройки:
https://yadi.sk/i/DhECBzNx3YzqhG

Трек завтра запишу и выложу.

**Comment by fokin33** [comment]
Возможно дело в настройке HDOP для записи равной 0.
Стоит указать какое-нибудь значение например как и в мониторинге 30, тогда точки не будут отбрасываться как неточные при записи в файл.

**Comment by progserega** [comment]
![screenshot_20180711-123830](https://user-images.githubusercontent.com/1297163/42549768-4673d13a-8511-11e8-9b4d-983b7e530b2c.png)
![screenshot_20180711-123857](https://user-images.githubusercontent.com/1297163/42549769-46a3b206-8511-11e8-803e-728f2191098e.png)
![screenshot_20180711-123905](https://user-images.githubusercontent.com/1297163/42549770-46d51aee-8511-11e8-942d-9bcf442f9bad.png)
![screenshot_20180711-123927](https://user-images.githubusercontent.com/1297163/42549771-4703c588-8511-11e8-9bd8-2eab9b8ed15b.png)
![screenshot_20180711-123944](https://user-images.githubusercontent.com/1297163/42549772-47326f00-8511-11e8-89e0-8416de5633d1.png)
![screenshot_20180711-124000](https://user-images.githubusercontent.com/1297163/42549773-47635dd6-8511-11e8-8d1c-1750779f0e04.png)
![screenshot_20180711-125617](https://user-images.githubusercontent.com/1297163/42549774-4795bf88-8511-11e8-80fb-c7c2d9fd7f8d.png)
![screenshot_20180711-125628](https://user-images.githubusercontent.com/1297163/42549775-47c73d06-8511-11e8-841f-37249dc3e126.png)
![screenshot_20180711-125634](https://user-images.githubusercontent.com/1297163/42549776-47f7342a-8511-11e8-91bb-04e19c4b8104.png)
![screenshot_20180711-125643](https://user-images.githubusercontent.com/1297163/42549777-4827df4e-8511-11e8-9b4b-a06581f1a52f.png)
![screenshot_20180711-125656](https://user-images.githubusercontent.com/1297163/42549778-4856a86a-8511-11e8-99e4-73ded21fac06.png)
![screenshot_20180711-125714](https://user-images.githubusercontent.com/1297163/42549779-488ab16e-8511-11e8-9c5a-2baad4f86235.png)
![screenshot_20180711-125755](https://user-images.githubusercontent.com/1297163/42549780-48b88e0e-8511-11e8-9519-bfcf6a56153e.png)
[2018-07-11_12-27_Wed.gpx.gz](https://github.com/OsMo-lab/OsMoDroid/files/2182877/2018-07-11_12-27_Wed.gpx.gz)
[debug-11-07-18.txt.gz](https://github.com/OsMo-lab/OsMoDroid/files/2182879/debug-11-07-18.txt.gz)

**Comment by progserega** [comment]
>> Возможно дело в настройке HDOP для записи равной 0.
Стоит указать какое-нибудь значение например как и в мониторинге 30, тогда точки не будут отбрасываться как неточные при записи в файл.

Во, как вариант! Попробую - отпишусь.

**Comment by progserega** [comment]
Выставил HDOP в 30 - трек начал писаться.
Смутило описание опции с именем "Максимальная погрешность HDOP":
"Метры. Минимальное расстояние между записью точек". По такому описанию легко можно поставить и 3 метра и 0.
Я думаю описание лучше сменить на примерно такое:
"Метры. Не сохранять точки в трек, если погрешность определения координат выше указанного значения".

**Comment by progserega** [comment]
К слову, в опциях записи трека указал путь сохранения "/sdcard/OsMoDroid" в результате трек у меня начал писаться по пути: "/sdcard/OsMoDroid/OsMoDroid" в списке треков все треки пропали и остался только вновь-записанный, но у него не работало отображение статистики - пустой экран был. После того, как очистил опцию "Путь для сохранения" и переместил новый трек - всё стало отображаться.
Записал новый трек - всё хорошо (с пустой отпций "Путь сохранения") - трек лёг как и нужно (по-умолчанию) в "/sdcard/OsMoDroid/".
