### ISSUE TITLE
Добавить кнопку SOS (можно опционально) на главный экран или в меню

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#4]
Во многих трекерах есть.
Должно посылать команду SOS, а далее сервер уже по настройкам аккаунта действует.
Кнопка только для авторизованных.

**Comment by GaMsh** [comment]
Актуальность возрастает в разы. Необходимо для командных групп очень

**Comment by fokin33** [comment]
Что слать по этой кнопке ?

**Comment by GaMsh** [comment]
Команду SOS, сервер сам решит как реагировать от настроек аккаунта
