### ISSUE TITLE
Отправка данных трекеру - пустые нули

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#44]
Раза три по моему говорили, но не записывали это в баг сюда)))

Вообщем OsMoDroid шлёт нули после точки, это плохо, потому что HDOP и Altitude мало того что целые числа только сервер берёт, так ещё и после . идёт бесполезный 0 =)

Мелочь, а глаз мозолит, если логи читать :)

T|L59.852982:30.373853A55.0H10.0

**Comment by fokin33** [comment]
Думал время на сервере по ГПС :-)
Добавил.

**Comment by GaMsh** [comment]
Время? оО Комментарий видать не к этому багу :)
