### ISSUE TITLE
Buffer function 

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#46]
Если включена опция "Передавать неотправленное" когда-то всегда с точками посылалось время в unixtime, а сейчас видимо этого нет, в результате чего при пропаже связи на карте точки из буффера выглядят как ёлочка туда сюда скачущая - скорей всего из-за рассинхронизации времени!
Надо бы поправить.

**Comment by fokin33** [comment]
Добавил.
