### ISSUE TITLE
Group chat

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#51]
Для получения сообщений используется команда GC:[group_u] она выдаёт последнии сообщения в порядке обратной сортировки.

Собственно тут всё просто. Отправитель известен только по имени, могу и device/uid выдавать, но не понял а надо ли... просто подставлять из списка юзеров ник нельзя, потому что человека может не быть онлайн, поэтому ник подставляет сам сервер, а не приложение.

Чтобы отправить сообщение используется примерно что то такое:
GCS:[group_u]|{"text":"Моё супер сообщение"}

Json нужен для избежания ошибок экранировки и переносов...

**Comment by GaMsh** [comment]
Обновило логику.
Есть 2 команды, приём и отправка по сути.
Также есть полл механзим уведомления.

В итоге, нынче стабильный формат выдачи из базы, в poll отправляется такой же объект, как и в БД сидят... 
В запросе GC:[group_u]|[offset_group_U]
offset group u - это u из сообщений

**Comment by GaMsh** [comment]
А тестировать проще всего через веб-интерфейс группы, там чат работает прекрасно

**Comment by fokin33** [comment]
bcdb61b4c78330b13139ecaa9d08de917adc6ad2

**Comment by GaMsh** [comment]
хм... а как оно работает? я нашел только отправку. никаких уведомлений и чата самого я найти не смог.
в списке юзеров его нет, осталась только строка и >> оО

**Comment by GaMsh** [comment]
Хм... ну всё-таки вынести надо в отдельную вкладку. и в уведомлении значёк заменить на OsMo чтобы было понятно от кого хоть уведомление то. Почему то на нексусе у меня это не работает, однако на 4 андроиде заработало...

**Comment by fokin33** [comment]
Отдельной вкладки не получится. На 5-м андроиде работает. 
Если что-то не работает надо логи.

**Comment by GaMsh** [comment]
Почему не получиться?

**Comment by GaMsh** [comment]
Насчет не работает это из-за PG, не парься
