### ISSUE TITLE
"Невидимые слои"

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#54]
Тыкаю в районе карты где написано "Нарвский округ", группа где трек проходящий там отключена, трека с wpt не видно, однако toast:
![2015-05-26 21 00 09](https://cloud.githubusercontent.com/assets/1438175/7829107/1ceedb10-0446-11e5-9eed-7c4da872763f.png)

Трек выключеннной группы не показывается на карте, как и точки из этого трека, однако пр инажатии на карту в том месте где расположены точки всплывает toast с названием точек!!!

Также скрытие контента групп почему-то не влияет на точки группы которые не связаны с треком, так и продолжает показывать.

**Comment by GaMsh** [comment]
Добавил скрин

**Comment by fokin33** [comment]
Поправлено
