### ISSUE TITLE
Нюансы первой установки

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#57]
Купил новый планш, обнаружил следующее неприятное..:

после установки key в памяти пустой, однако osmodroid долбиться с ним на сервер (init) и получает wrong device, после чего уже запрашивает ключ...неприятно это тем что не быстро происходит подключение. на медленном интернете + задержки между командами + не знающий человек не поймет фигли реконнекты идут. хотя все в конечном итоге будет успешно, это томное ожидание и неясность мне не нра...
как вариант при пустом key инит не делать + выдаваать алерт, мол для начала работы приложение должно успешно соединиттся с сервером, мол не кипешуйте, просто подождите минутку...

**Comment by fokin33** [comment]
Не знающий человек и не поймет что там что-то реконнектило. 
Можно конечно при пустом ключе сразу делать инит, но чего-то я опасаюсь там трогать, посмотрю.

**Comment by GaMsh** [comment]
Однако что то типа "дождитесь пока значёк позеленеет" наверное можно написать

**Comment by fokin33** [comment]
Сейчас уже сразу при первой установке делается запрос.
