### ISSUE TITLE
Авторизация...

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#58]
Все таже история про новый планш... после того как все таки он подключился с пятокого коннекта окончательно, я авторизуюсь...

и тут удивление меня посетиило, то ли кеш то ли еще чего, но после авторизации я смог увидеть свои группы и девайсы только после перезапускаьприложения, кнопка обновить не помогала даже...
примерно подобное описывал один из юзеров. надо внимательно проверить, может добавить очистку кешей и перевыполнение всех команд типа device, group, link чтобы инфа сразу подсосалась...

**Comment by fokin33** [comment]
Так и сделано, после авторизации идет реконнект. Видимо чего-то со стороны сервера не вернулся список сразу. Если повторится надо смотреть логи

**Comment by GaMsh** [comment]
Ещё раз подтверждаю данный баг. После авторизации гостевого устройства, делается INIT, PG:1, DEVICE, а GROUP нет :( В результате - сервер шлёт координаты, а точка безымянная и список групп пуст!

**Comment by fokin33** [comment]
Добавлена очистка групп и устрйоств при завершении авторизации. Если до этого список был заполнен запрос групп и устройств не делался. Теперь он принудительно очищается.
