### ISSUE TITLE
PG:-1 PD:-1

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#59]
Обнаружил следующий нюанс... не знаю как решить.
Когда выключена галочка "обновлять карту в фоне" все события фильтруются, соответственно, когда человек посмотрит на карту списки юзеров-треков-точек могут быть не актуальны и получается надо после входа на карту делать DEVICE GROUP запросы. Единственное чтобы от хождения по вкладкам не высосало весь интернет задержку хотя бы минутную (лёгкий кеш) я бы сделал.
Хотя задержка тоже может навредить. И тут надо думать о цели отключения подписки, чтобы в коннект не сорили, но раз получить 10 кб при включении карты впринципе норм, но с другой стороны несколько раз вкладки прокликал и уже 100 накликал... Вообщем надо подумать.

**Comment by GaMsh** [comment]
Для возможности обновления и некой экономии трафика я сделал команду аналог GROUP, но выдающую только активные группы - GAG формат идентичен, но выдаёт только активные. Например после включения PG:1 хорошо бы делать данный запрос, ибо регулярно нарываюсь на не сихнонизированность списка юзеров из-за чего не вижу людей на карте

**Comment by GaMsh** [comment]
Команду GAG убрал, обновил просто GROUP, она выдаёт обзорную информацию по неактивным группам и полную по активным.
А GA выдаёт полную информацию об активируемой группе.

**Comment by fokin33** [comment]
Я так понял по данному вопросу ничего в клиенте менять не надо?

**Comment by GaMsh** [comment]
В теории да, на практике проблем если не возникло от нового поведения команд!

**Comment by fokin33** [comment]
Закрываем?

**Comment by GaMsh** [comment]
Пока не знаю... надо всё проверить цепочки по кругу. Хотя наверное да, ибо это уже вопрос сервера по сути.
