### ISSUE TITLE
Добавить в signin параметр key (device key)

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#60]
https://osmo.mobi/signin?type=m&key=XXXXXXX без key скоро работать не будет! именно type=m, который в новых клиентах.

**Comment by fokin33** [comment]
Что то я такой команды не использую, где оно применяется?

**Comment by fokin33** [comment]
Нашел. 2f6fa8797c154c4fde1f4b997dde76f18f6905e2
