### ISSUE TITLE
Вывод скорости участника из группы!

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#61]
Насколько я помню если скорость ниже 1 м/с она у нас не выводиться.
Поймал ситуацию, что на предыдущей координате скорость была 7 км/ч, а все последующие микродвижение и скорость приходит = 0, однако точка двигается, а над точкой как было 7 (км/ч) так и висит, подозреваю что исправить только если скорость станет вновь больше 1 м/с.
Надо бы поправить, мелочь, а вопросы могут возникнуть.

**Comment by GaMsh** [comment]
Исправляли?

**Comment by fokin33** [comment]
да
