### ISSUE TITLE
Update map on the background

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#64]
Я думаю данная галочка "бесполезна", я думаю её можно напрямую связать с галочкой "показывать следы за участниками". Просто и логично.
Только проблему рассинхрона сначала надо решить: https://github.com/OpenStreetMap-Monitoring/OsMoDroid/issues/59

**Comment by GaMsh** [comment]
Идея всё таже, логично и просто.

**Comment by fokin33** [comment]
Да все правильно сейчас. Разные совершенно настройки, нет смысла их объединять.
Одна показ следов - щелк щелк на ходу. Вторая про получение координат в принципе.

**Comment by GaMsh** [comment]
Не думаю что правильно. ПОтому что без одной галки вторая толком не работает, свернул карту - след получается со сгрублениями, бывает значительными, которые сильно мешают.

**Comment by fokin33** [comment]
Еще раз ) Если я хочу видеть следы, я хочу их вклчюать отключать. Прием координат в фоне к этому не относится. То что координаты из за этого скачут, ну тут уж извините - но запрещать из за этого включать показ следа я не буду )

**Comment by GaMsh** [comment]
Однако я тебе ещё раз повторяю, что две галочки тут не нужны и они вводят пользователей в заблуждение. И логики в том что их две нет. Ибо по сути это одно действие, зачём ещё получать координаты в фоне, кроме как не для наблюдения следа?
