### ISSUE TITLE
Ошибка исчёкшей авторизации

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#65]
При получении токена (init) если user key протух сервер теперь выдаёт ошибку, также он выдаёт ошибку если авторизация отличается от того user id к которому привязано устройство.
Пока пришлось отключить так как клиенты затыкается и стоит ступором.

Эта ошибка отличается от удалённого устройства (ошибка 100), когда нужно делать полный сброс.

Тут другая ситуация, если ошибка 67, 68 или 69, нужно вывести форму авторизации мол авторизуйся.

**Comment by fokin33** [comment]
Что то я подумал что и на ошибку 100 автоматом получать все новое на устройство плохо.
Надо бы чегонить вывести так же и там уже кнопку показать - сбросить данные ?

**Comment by GaMsh** [comment]
Не, я о ключе юзера, а не устройства. Потому надо просто сказать аля "чтобы пользоваться данным устройством войдите под своим логином" (могу выдавать ник юзера) и давать форму signin

**Comment by fokin33** [comment]
Непонятно на самом деле. Вот отправляю я запрос на получение токена, а пользовательский ключ протух. Но устройство то живо, по идее надо давать токен для соединения, но и какую то информацию о том что авторизация нужна заново. Тогда клиент продолжит работу как не авторизованный, и у себя вернет кнопку авторизации на место - надо будет человеку, нажмет и авторизуется заново. Предупржедение об этом можно и показать, но останавливать из за этого работу клиента очень неудобно - весь цикл рушится соединения с сервером.

**Comment by GaMsh** [comment]
Беда в том что когда ты первый раз авторизуешься, устройство привязывается. и уже после привязки давать без юзер клбча доступ к данным не получиться, так как уже выдаются данные и устройство и пользователя. (группы например в момент привязки мигрируют к юзеру).

Потому или мол введите пароль от юзера или сброс устройстваа и живем как аноним с чистого листа.

**Comment by GaMsh** [comment]
Этот баг не действителен, потому что теперь привязанный device - сам является ключём к аккаунту и user по сути одноразовый ключ, но чтобы не терять совместимость со старыми версиями - я это не трогал.
