### ISSUE TITLE
Тайловый слой по умолчанию

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#66]
Спутник плох тем что он показывает русские названия в других странах и долго обновляется, нашёл получше вариант, его лучше бы добавить и сделать по-умолчанию.

http://[a,b,c].tile.thunderforest.com/outdoors/[z]/1195/593.png

**Comment by fokin33** [comment]
f9221b8a3282f28c64598c245aa92f1814d131c3
