### ISSUE TITLE
Заедание GPS при работе с OsMoDroid

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#67]
Много раз ловил данный глюк, надо бы проверить код работы с gps, почему-то андроид клинит.
Самое плохое, что данную жалобу я получил уже с нескольких десятков пользователей!

**Comment by fokin33** [comment]
Так добавляли же логирование, есть логи заедания ?

**Comment by GaMsh** [comment]
да, но я не вижу в них нифыига, вышлю... с темой "заедание"

**Comment by GaMsh** [comment]
Кстати заметил закономерность, что заедние вполне часто происходит если частота отправки более 5-6 секунд (другие параметры по 0). Если чаще проблема не повторяется.
Логи отправил в почту.
