### ISSUE TITLE
Перехват новых url osmo.mobi

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#68]
Необходимо сделать перехват адресов вида:
- http://osmo.mobi/g/vahvah
  С выводом формы вступления в группу. И подстановкой vahvah в форму как ID
- https://osmo.mobi/u/[A-Z](10+) (постоянная ссылка)
  С выводом формы привязки устройства.

**Comment by fokin33** [comment]
нужны подробности

**Comment by GaMsh** [comment]
Ну в случае с g просто vahvah в существующую форму подставляешь и всё.

Про привязки пока думаю. Старых не существует, но есть мысль сделать возможность подписки на тоже самое что ты смотришь в браузере, аля, чтобы использовать приложение как монитор чистой воды и чтобы срабатывало "открыть с помощью", но пока думаю.
