### ISSUE TITLE
Экран статистика в режиме локальной работы и трек на карте

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#69]
Тут возникла дискуссия про оффлайн работу приложения: https://plus.google.com/110371246826482773671/posts/DX3jwYEbszT

В кратце, если отключить онлайн мониторинг - экран статистика странно работает, а скорее не работает и сие не логично.
На карте хорошо бы иметь возможность выводить свою линию даже при локальной работе, подробнее свои мысли я описал в гугл+

**Comment by fokin33** [comment]
Да там есть перепутанность, часть параметров завязана на онлайн, надо упорядочить. При переезде на osmo.mobi поломалось

**Comment by GaMsh** [comment]
Ждём фикса

**Comment by fokin33** [comment]
bcdb61b4c78330b13139ecaa9d08de917adc6ad2
