### ISSUE TITLE
"Мониторинг на устройстве "ххх" запущен"

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#73]
Выскакивает на это: GP:2643|{"users":[{"u":"1665","name":"GaM","color":"#ff0000","state":"0"}]}
Каком боком? Тут даже state 0

**Comment by fokin33** [comment]
Так как постепенно пропали все работавшие ранее оповещения, а функция мне нужна,  переделал на оповещение если каким то образом пришли новые координаты то выходит оповещение. Проверял, работает как нужно. Всегда можно отключить оповещение в настройках программы если мешают.

**Comment by GaMsh** [comment]
Однако как я понял оно на GP реагирует, ибо координат не было, только GP.

**Comment by GaMsh** [comment]
И это совершенно не правильно. Ибо сервер присылает GP об статусе онлайн и о статусе мониторинга, вот их и надо использовать. Правда раздел оповещения вообще место только занимает имхо.

**Comment by GaMsh** [comment]
И проблема усугубляется тем что оповещения по умочланию отключены. Людям как бы не до разбирайтельства с настройками, они хотят всё из каробки

**Comment by GaMsh** [comment]
Не блин... убери эту ахинею. Я просто включил один из телефонов в группе (который включаю раз в месяц) (осмодроид в автозагрузке), прилетел GP и мне сразу куча оповещений о том что мониторинг запущен, причём время текущее. Что деориентирует. Да и мониторинг никто не запускал, в GP информацию о выходе онлайн в группу просто.
Уведомления для групп работают сейчас по аналогии с устройствами, а то что ты сделал не даёт пользоваться нормально, если уведомления включены. Путает и порождает вопросы кто что и где запустил. А ответа искать негде.
Вкрайняк ты себе же бранчнуть сборку можешь, с какими угодно для себя уведомлениями. а жалобы от людей уже ...
