### ISSUE TITLE
preloader

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#74]
Хорошо бы при наличии в очереди не исполненных команд менять значек программы на тпкой, чтобы было ясно, что идет обмен данными...

**Comment by fokin33** [comment]
На какой ?

**Comment by GaMsh** [comment]
Ну в идеале гифку чтобы мерцал напримен глазик. Могу изготовить.

**Comment by GaMsh** [comment]
Мне только знать надо что гиф можно или нет!

**Comment by fokin33** [comment]
гиф нельзя, попробую сделать чтобы он просто крутился пока есть команды в очереди.

**Comment by GaMsh** [comment]
менять одну на другую можно? например с зелёной заливкой на синию и чередовать. значком моргать - неправильно с точки зрения дизайна лого :)
