### ISSUE TITLE
При выходе из группы она не стирается из списка!

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#76]
Тут по сути варианта два - убирать конкретную группу или запрашивать весь список заново!

Сейчас помогает только ручное обновление.
Кстати хорошо бы выдавать вопрос "вы уверены?", а то случайно нажать можно.

![screenshot_20151104-210749](https://cloud.githubusercontent.com/assets/1438175/10947683/675bd4c8-833a-11e5-8efd-615449c09f66.png)
![screenshot_20151104-210740](https://cloud.githubusercontent.com/assets/1438175/10947684/676a543a-833a-11e5-8ad7-a8fe80626db0.png)

**Comment by fokin33** [comment]
Лог?

ср, 4 нояб. 2015, 21:24, Moshkov Konstantin notifications@github.com:
