### ISSUE TITLE
Упрощение настроек трекинга

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#80]
Есть мысль упростить настройки... во первых как писал ранее заменив милисекунды на секунды и ползунки обычные андроидовские, вместо полей ввода.
Так и добавлением режима автоматических настроек, во многих навигаторах это есть и по сути ничего сложного в этом нет.

Например если устройство стоит более 30 секунд мы снижаем частоту отправки координат, если стоит более 5 минут ещё снижаем, если едет быстрее 60 км/ч - повышаем.
Есть также мысль задействовать motion sensor, правда он есть батарейку, но стандартный кейс - устройство было долго статичным и вдруг его тронули и поменялась хоть на чуть-чуть скорость - активируем более частую передачу. Можно включать опрос сенсора скажем только если скорость долго равна 0.

В целом представляется так:
стандартный интервал - 5 секунд или измение курса на более чем 45 градусов при скорости выше 10 км/ч
выше 20 км/ч - 4 секунды
выше 60 км/ч - 2 секунды
выше 80 км/ч - 1 секунда

скорость = 0 более 30 секунд - частота 10 секунд
скорость = 0 более минуты - частота 15 секунд
скорость = 0 более 3-х минут частота 60 + активация по motion sensor

Это мои мысли примерные, допускаю не конкретно такие числа, но в общем надо потестировать.

Для чего это вообще надо? Многие к сожалению меняют стандартные настройки и в итоге ничего не работает, так как устанавливаются противоречащие друг другу значения, а защиты от дурака нет.
Понять настройки текущие не так то просто, а стандартный интервал нагружает сервер, особенно это плохо тем, что многие пользователи круглосуточно не выключают трекинг и получается, что OsMoDroid шлёт с большой частотой просто по сути "одни и теже" координаты или с мини-изменениями из-за дрифта приёмника... Это также нагружает трафик всем тем, кто эти координаты получает, хотя сервер нынче фильтрует скорости ниже 1 м/с, для групп.

**Comment by GolexNsk** [comment]
"Для чего это вообще надо?... защиты от дурака нет. Понять настройки текущие не так то просто, "

Коллеги, подумайте над профилями настроек под модель использования. Например: "Пешеход", "Велосипедист", "Автомобиль", "Экономим батарею". Некоторые профили зашить намертво, остальные могут настраивать пользователи.
