### ISSUE TITLE
Удаленные команды для чтения/сохранения настроек

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#84]
Тут вроде и так все ясно, как ранее было.
С одной поправкой, в настройки бы эти еще добавить вид карты, ну мапник, мапсурс, чтрбы сервер мог узнать и изменить, достаточно названия источника.

**Comment by fokin33** [comment]
Добавлено
        public static final String TRACKER_GET_PREFS = "43";
        public static final String TRACKER_SET_PREFS = "44";
Надо пробовать.
