### ISSUE TITLE
Show traces

### ISSUE THREAD

**Issue by jluttine** [OpenStreetMap-Monitoring/OsMoDroid#87]
Hi, and thanks for this cool app! I'd like to make a feature proposal: Make user traces visible at osmo.mobi (and osmand) so that you'd not only see the current locations but also the track they've travelled. I think this would be very interesting in, for instance, orienteering competitions etc.

Of couse, this could be extended to support various ways of analyzing and looking at the history (slider to move in time, speed at particular time etc etc). But at least showing the trace would be very nice. There are tools for analyzing GPX traces ones you've uploaded them, so only some basic trace analysis which is interesting in real-time would be sufficient.

**Comment by GaMsh** [comment]
This repoaitory of app OsMoDroid, osmabd and etc not be here.
