### ISSUE TITLE
Модифицировать SM

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#89]
Когда открываем карту посылается команда SM, хорошо бы её модифицировать чтобы посылались данные о том какое место сейчас в центре, что-то вроде:

SM|{"lat":60.123456,"lon":30.654321,"zoom":14} 

Посылать постоянно не требуется, но при передвижении карты на пару км-экранов (может от зума выбирать дистанцию) - посылать было бы полезно. Интересно изучать на что смотрел пользователь и что он видел. Также от этого могут быть какие-то автоматические действия в будущем.

**Comment by GaMsh** [comment]
Всё хорошо, кроме лошадиных float =)

`{"lat":59.90477895931818,"lon":30.351104736328125,"zoom":11,"bbox":"N:59.995209238977495; E:30.474700927734375; S:59.814101743487946; W:30.227508544921875","mapid":1}`

**Comment by GaMsh** [comment]
Так и осталось!

**Comment by GaMsh** [comment]
Ныне так: {"lat":"59.90891","lon":"30.29274","zoom":10,"bbox":"N:60.0895020074871; E:30.539932250976563; S:59.72733118833153; W:30.045547485351563","mapid":1}

lat lon я думаю вовсе не нужны, результирующе как-то так:
{"zoom":10,"bbox":"N:60.08950; E:30.53993; S:59.72733; W:30.04554","mapid":1}

**Comment by GaMsh** [comment]
и кстати почему не "bbox":"60.08950,30.53993;59.72733,30.04554", но это уже мелочи)

**Comment by fokin33** [comment]
поправил
