### ISSUE TITLE
Реализовать RC:30

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#91]
Данная команда должна возвращать на сервер статус сигнализации 1 или 0, включена или нет.

**Comment by fokin33** [comment]
Так сделано же. Или не работает ?

**Comment by GaMsh** [comment]
Проверю

**Comment by GaMsh** [comment]
Где-то видимо у тебя пробел пропущен или опечатка, команда прилетает битая!

RCR:30true
RCR:30false

И кстати лучше 1 или 0 !
