### ISSUE TITLE
Модифицировать данные при записи трека

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#92]
Посмотрел записываемый трек...
Пример точки:
```
<trkseg>
<trkpt lat="59.852802" lon="30.373166">
<ele>31.0</ele>
<time>2016-09-25T21:36:56Z</time>
<speed>0.2</speed>
<hdop>0.8</hdop>
</trkpt>

```
ele всегда с нулём в конце, можно сделать просто int, без числа после запятой.
hdop также полезно округлять до целового числа.

Вроде бы мелочь, но при файле 5 МБ лишних нулей уже многовато :)

**Comment by GaMsh** [comment]
Заметил только сейчас, что xml схавался, обновил разметку в сабже

**Comment by fokin33** [comment]
Округлил все до целого
