### ISSUE TITLE
Новые типы уведомлений GP

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#95]
GP:1234|{"near":{"type=>"user", "nick"=>"Vasya", "dst"=>341}, {"type"=>"waypoint", "name"=>"Центр вселенной"}

В текстовом виде должно быть что-то вроде "Вы близко к пользователю/точке [name] ([dst] m)"

GP:1234|{"alarm":{"gu"=>123,"nick"=>"Vasya","mode"=>1,"time"=>000000000}

Текстовый вид: сработала сигнализация у [nick] в группе [group]

**Comment by fokin33** [comment]
Это всегда будет объект или возможно что массив придет ?

**Comment by GaMsh** [comment]
в GP массив может быть только в обьекте юзера - массив координат хвостика, то естьь в дочернем элементе массива

**Comment by GaMsh** [comment]
Вот пример из лога OsMoDroid:
2016-12-19 03:09:01 GP:4971|{"near":[{"u":132,"type":"user","nick":"Vasya","dst":"228","time":1482106191,"e":"86181"},{"u":3221,"type":"waypoint","name":"Home ofVasya","dst":"50","time":1482106191,"e":"86182"}],"geoevent":[{"u":1,"type":1,"geozone":1,"name":"TEST","nick":"BOT","time":1482106191}]}

**Comment by GaMsh** [comment]
Near пробелов не имеет.
Аларм сделан?

И да, для геозон уведомление если на самого себя приходит можно текст типа "Вы вошли в геозону ХХХ", "Вы вышли из геозоны ХХХ"...

**Comment by fokin33** [comment]
Всмысле нет пробелов?
Для аларм нужен тоже пример как придут данные.

21 дек. 2016 г. 13:09 пользователь "Moshkov Konstantin" <
notifications@github.com> написал:

**Comment by GaMsh** [comment]
Вывод near без пробелов, пример аларма в первом сообщение же
![screenshot_2016-12-20-21-18-04](https://cloud.githubusercontent.com/assets/1438175/21385895/6990ba92-c781-11e6-8c93-42c4b834b150.png)

**Comment by fokin33** [comment]
Вроде поправил, добавил Аларм

**Comment by GaMsh** [comment]
К near небольшое дополнение...
как и с геозонами пущай будет mode 1/0
Если 1 значит приблизились, если 0 отдаляемся.
Штатно таких уведомлений не будет по умолчанию, но иногда могут быть полезны.

И на этом задачу можно закрывать. Alarm пока не проверял, проверю в купе с 1/0 для near.
Для waypoint поддержка реализована?

**Comment by GaMsh** [comment]
Кстати да, заметил путаницу с name/nick, если речь о имени юзера я использую nick, если например точка или еще чего то название в name

**Comment by fokin33** [comment]
Готово

**Comment by GaMsh** [comment]
Уточнения информации:

Near user:
Vasya приблизился к Olya (Vasya можно выдернуть по gu, если он наш надо написать "Вы")
$event = array('u' => $gu, 'type' => 'user', 'id' => $near, 'mode' => 1, 'nick' => 'Olya', 'dst' => '123 m');

Near waypoint:
Vasya рядом с "Магазин Конфет" (Vasya можно выдернуть по gu, если он наш надо написать "Вы")
$event = array('u' => $gu, 'type' => 'waypoint', 'id' => $near, 'mode' => 1, 'name' => 'Магазин Конфет', 'dst' => '25 m');

Alarm:
Сработала сигнализация у Vasya
$event = array('u' => $gu, 'mode' => 1, 'nick' => 'Vasya')
