### ISSUE TITLE
Alarm

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#96]
По некоторым тестам получается, что сигнализация не работает если OsMoDroid отсоединился от сервера, но я могу ошибаться. Однако без опции постоянного соединения ничего не происходит, если приложение успело отключиться.

**Comment by GaMsh** [comment]
Вроде как поправлено?

**Comment by GaMsh** [comment]
Поправлено, но костылём видимо или так и задумано?
По моим наблюдения, если включить сигнализацию - коннект не засыпает, а поддерживается постоянно...

**Comment by fokin33** [comment]
Нет, если включена сигнализация коннект не поддерживается.
Все так же как и было ранее., единственное изменение что при срабатывании сигнализации делается обработка как будто пришло сообщение по GCM - создается соединение и идет отправка после подключения. Если в каких то ситуациях остается висеть коннект - нужны логи.

**Comment by GaMsh** [comment]
Ок, понял, повторю тест

**Comment by GaMsh** [comment]
Тест не смог повторить пока, но замечена странность. 
Я ставлю на сигнализацию через само приложение кнопкой на главном экране, срабатывает сигнализация, я отключаю её и режим сигналки кнопкой. Однако ещё раз если потеребить телефон он снова шлёт ALARM и всё по-новой, хотя сигнализацию я уже выключил! оО

**Comment by GaMsh** [comment]
Так, из фонового вроде работает как надо.
Глюк с выключением сигналки то есть то нет, пока не понял закономерности!

**Comment by fokin33** [comment]
Попробуй при запущенном мониторинге потестить - будет ли разница ?

**Comment by GaMsh** [comment]
И при запущенном вроде нормально теперь
