### ISSUE TITLE
Парсинг треков групп

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#97]
Криво парсит треки, где много trkseg.
См скрин.
Нельзя их упрощать как одно целое. Лучше вовсе не упрощать сегменты меньше 50 точек скажем...
![screenshot_2016-12-16-10-42-51](https://cloud.githubusercontent.com/assets/1438175/21297625/74384ef4-c594-11e6-89cc-62577a6b2ef8.png)
![screenshot_2016-12-16-10-43-34](https://cloud.githubusercontent.com/assets/1438175/21297633/85df1714-c594-11e6-8bf7-a5fa62a57448.png)
![screenshot_2016-12-16-10-43-48](https://cloud.githubusercontent.com/assets/1438175/21297637/95eacd6a-c594-11e6-91df-dbfe5ad74bb9.png)

**Comment by GaMsh** [comment]
Группа пример: https://osmo.mobi/g/ehrwsssaipxxareh

**Comment by fokin33** [comment]
Сейчас тег trkseg вообще не читается из gpx файла - при разработке как то не думалось что такие файлы будут грузить (сам осмодроид пишет все в один сегмент), надо  подкрутить,, пока не придумал как - объект трека в осмодроиде просто список точек.

**Comment by GaMsh** [comment]
ну у меня когда-то также было, а таких треков много. всякие gpsies.com такие создают, да и османд...

Надо просто каждый trkseg парсить как отдельный трек, на сайте я именно так и сделал.

**Comment by GaMsh** [comment]
Есть успехи?

**Comment by fokin33** [comment]
Готово
