### ISSUE TITLE
При возврате ошибки действие метода не должно продолжаться...

### ISSUE THREAD

**Issue by GaMsh** [OpenStreetMap-Monitoring/OsMoDroid#98]
Самый простой пример - попробовать выйти из группы семья будучи ее владельцем или попробовать ее выключить!
![screenshot_2016-12-21-11-21-26](https://cloud.githubusercontent.com/assets/1438175/21385297/ff23f400-c77e-11e6-8f5f-06728d230b32.png)
![screenshot_2016-12-21-11-21-30](https://cloud.githubusercontent.com/assets/1438175/21385304/04083d96-c77f-11e6-8b5f-962321be6786.png)
А группа исчезла... после рефреша списка конечно же она на месте, так как сервер не принял действие.

Собственно это верно для любых команд, что нужег положительный ответ сервера прежде чем делать какие-то визуальные действия...

**Comment by fokin33** [comment]
Есть какой от общий признак что ответ сервера был ошибочным и его не надо обрабатывать?

**Comment by GaMsh** [comment]
так вместо результата с данными там error и error_description

**Comment by fokin33** [comment]
ОК, если есть error то обработка команды не производится.
